name: 'Git-Test Setup'
author: '@awseward'
description: Set up Dhall for use in a GitHub Action

# TODO
# inputs:

runs:
  using: composite
  steps:
    - shell: bash
      # TODO: Break this down so it can be parameterized
      run: |
        dhall_haskell_ver='1.40.2'
        bin_zip_name="dhall-${dhall_haskell_ver}-x86_64-linux.tar.bz2"
        wget "https://github.com/dhall-lang/dhall-haskell/releases/download/${dhall_haskell_ver}/${bin_zip_name}" \
          && tar -xjvf "./${bin_zip_name}" \
          && rm -rvf "./${bin_zip_name}"

        dhall_json_ver='1.7.9'
        bin_zip_name="dhall-json-${dhall_json_ver}-x86_64-linux.tar.bz2"
        wget "https://github.com/dhall-lang/dhall-haskell/releases/download/${dhall_haskell_ver}/${bin_zip_name}" \
          && tar -xjvf "./${bin_zip_name}" \
          && rm -rvf "./${bin_zip_name}"

        dhall_yaml_ver='1.2.9'
        bin_zip_name="dhall-yaml-${dhall_yaml_ver}-x86_64-linux.tar.bz2"
        wget "https://github.com/dhall-lang/dhall-haskell/releases/download/${dhall_haskell_ver}/${bin_zip_name}" \
          && tar -xjvf "./${bin_zip_name}" \
          && rm -rvf "./${bin_zip_name}"

        # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#example-8
        echo "$(pwd)/bin" >> $GITHUB_PATH

        mkdir -vp "${HOME}/.cache"

    - shell: bash
      run: |
        type dhall && dhall --version
        type dhall-to-yaml && dhall-to-yaml --version
        type yaml-to-dhall && yaml-to-dhall --version
